# Generated by Django 2.2.6 on 2019-11-11 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rede', '0003_auto_20191111_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
